services:
  - type: web
    name: librechat
    env: node
    buildCommand: npm ci && npm run build:all
    startCommand: npm run backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        sync: false
      - key: PORT
        value: 3080
      - key: MONGO_URI
        sync: false
      - key: CREDS_KEY
        sync: false
      - key: CREDS_IV
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: CHECK_BALANCE
        sync: false
      - key: SESSION_EXPIRY
        value: 900000
      - key: REFRESH_TOKEN_EXPIRY
        value: 604800000
